### ISSUE TITLE
Clicking on the time picker is showing "invalid" inside a survey.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OPGRuntime#1]
Please find the survey url below.
http://1pt.mobi/16yu12

Scenario:
1. Start the survey. Click on the date picker and time picker to set the date and time respectively. For the first time it will work fine.
2. Click Next. 
3. Click Previous. Now click on the time picker again.
It will shows invalid for all three fields (hour, minute and AM/PM).

**Comment by dougmorris** [comment]
@onepointpb this seems to be working now.

**Comment by onepointpb** [comment]
The time picker is modified to fix this issue.
